apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
  labels:
    app: aspnet-core-multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: multi-container
  template:
    metadata:
      labels:
        component: multi-container
    spec:
      containers:
        - name: container-webui
          image: testappwebui
          imagePullPolicy: Never
          ports:
            - containerPort: 80
        - name: container-webapi
          image: testappwebapi
          imagePullPolicy: Never
          ports:
            - containerPort: 81
          env:
            - name: ASPNETCORE_URLS
              value: http://+:81